version: "3.4"
services: 
    api:
        user: 1000:1000
        container_name: wa_labs_api
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dev
        ports: 
            - 3000:3000
        volumes: 
            - ./:/app
        links: 
            - postgres
        depends_on: 
            - postgres
            
    postgres:
        user: 1000:1000
        container_name: wa_postgres
        image: postgres:9.4
        environment:
            POSTGRES_PASSWORD: wa-lab
            POSTGRES_USER: wa-lab
            POSTGRES_DB: wa-lab
            PGDATA: /var/lib/postgresql/data/pgdata
            #PGDATA: /pgdata

        ports:
            - "5432:5432"
        volumes:
            - ./.data:/var/lib/postgresql/data
            #- ./.data:/pgdata
            - ./docker/postgres/test_db.sql:/docker-entrypoint-initdb.d/test_db.sql
    adminer:
        image: adminer
        restart: always
        depends_on:
            - postgres
        links:
            - postgres
        ports:
            - "8081:8080"    
    
    
